# Generated by Django 4.2.7 on 2023-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_remove_profile_birthdate_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
