# Generated by Django 4.2.7 on 2023-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0003_remove_profile_location_profile_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
