# Generated by Django 4.2.7 on 2023-11-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0006_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
