# Generated by Django 4.2.7 on 2023-11-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0007_rename_likes_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
