# Generated by Django 4.2.7 on 2023-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0016_alter_post_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_img',
            field=models.ImageField(default='profile_images/blank-profile-picture.png', upload_to='profile_post_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='profile_images/blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
