# Generated by Django 4.2.7 on 2023-11-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0017_profile_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tel',
        ),
    ]
