# Generated by Django 4.2.7 on 2024-11-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0017_alter_post_user_img_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backgroundimg',
            field=models.ImageField(default='background-img/img1.jpg', upload_to='background-img'),
        ),
    ]
