# Generated by Django 4.2.7 on 2024-11-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0018_profile_backgroundimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='backgroundimg',
        ),
    ]
